# Generated by Django 5.1.5 on 2025-01-31 08:31

import configs.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[configs.settings.file_upload_validator]),
        ),
    ]
