# Generated by Django 5.1.5 on 2025-02-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_email'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='parsed_text',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='resume.resumefile'),
            preserve_default=False,
        ),
    ]
