# Generated by Django 5.1.5 on 2025-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_parsed_text_alter_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
