# Generated by Django 5.1.5 on 2025-02-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_parsed_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
    ]
