# Generated by Django 5.1.5 on 2025-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_skill_candidateskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CandidateSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
