# Generated by Django 5.1.5 on 2025-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardandcertification',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
