# Generated by Django 5.1.5 on 2025-02-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_awardandcertification_parsed_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateskill',
            old_name='parsed_text',
            new_name='parsed_skill',
        ),
    ]
