# Generated by Django 5.1.5 on 2025-02-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_rename_parsed_text_candidateskill_parsed_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateskill',
            old_name='parsed_skill',
            new_name='parsed_skills',
        ),
    ]
