# Generated by Django 5.1.5 on 2025-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_rename_parsed_skill_candidateskill_parsed_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50, null=True),
        ),
    ]
