# Generated by Django 5.1.5 on 2025-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_alter_candidateskill_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='parsed_edu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
