# Generated by Django 5.1.5 on 2025-02-03 12:00

import config.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[config.settings.file_upload_validator])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
