# Generated by Django 5.1.5 on 2025-02-18 09:02

import apps.resume.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[apps.resume.validators.file_upload_validator]),
        ),
    ]
