# Generated by Django 5.1.5 on 2025-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='parsed_awards_and_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumefile',
            name='parsed_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumefile',
            name='parsed_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumefile',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
